FROM ubuntu

EXPOSE 80

RUN apt update && apt install update  && apt install -y apache2 
RUN apt-get install systemd -y

## para o apache precisei determinar um Dominio name, usei a flag -h nome do dominio
