version: '3.3'
services:

  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "9090:80"

    volumes:
      - ./www:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf

    networks:
      frontend:
        ipv4_address: 172.29.0.40

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'login'
      MYSQL_PASSWORD: 'senha123'
      MYSQL_ROOT_PASSWORD: 'senha123'

    ports:
      - '3306:3306'

    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

    networks:
      frontend:
        ipv4_address: 172.29.0.50
volumes:
  my-db:


networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
