version: '3'

services:
  db:
    image: mysql:latest
    volumes: 
      - x-db_data:/var/lib/mysql # Correção: alterar nome do volume para 'x-db_data'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=teste
      - WORDPRESS_DB_PASSWORD=teste
      - WORDPRESS_DB_NAME=wordpress

volumes:
  x-db_data: {} # Correção: adicionar prefixo 'x-' e definir um valor vazio para o volume
