version: '3.7'

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./docker-registry:/var/lib/registry
    networks:
      my-network:
        ipv4_address: 172.16.238.2 

  registry:
    image: 7621ed3504d4
    restart: always
    container_name: registry_ui
    ports:
      - "8888:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=localhost
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
    networks:
      my-network:
        ipv4_address: 172.16.238.3
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/29
